additionalProperties:
  gemAuthor: duffn
  gemAuthorEmail: 3457341+duffn@users.noreply.github.com
  gemDescription: Learn about engineering metrics and improve your software delivery performance with the Athenian API.
  gemHomepage: https://github.com/duffn/athenian
  gemLicense: MIT
  gemName: athenian
  gemSummary: A library for working with the Athenian API.
  moduleName: Athenian
enablePostProcessFile: true
