=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.81 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.81.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0
=end

require 'spec_helper'
require 'json'

# Unit tests for Athenian::GetApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GetApi' do
  before do
    # run before each test
    @api_instance = Athenian::GetApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetApi' do
    it 'should create an instance of GetApi' do
      expect(@api_instance).to be_instance_of(Athenian::GetApi)
    end
  end

  # unit tests for get_contributors
  # List all the contributors belonging to the specified account.
  # @param id Numeric identifier of the account.
  # @param [Hash] opts the optional parameters
  # @return [Array<Contributor>]
  describe 'get_contributors test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_jira_issues
  # Retrieve Jira issues by key.
  # @param [Hash] opts the optional parameters
  # @option opts [GetJIRAIssuesRequest] :get_jira_issues_request 
  # @return [GetJIRAIssuesResponse]
  describe 'get_jira_issues test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_prs
  # List pull requests by repository and number.
  # @param [Hash] opts the optional parameters
  # @option opts [GetPullRequestsRequest] :get_pull_requests_request 
  # @return [PullRequestSet]
  describe 'get_prs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_releases
  # List releases by repository and name.
  # @param [Hash] opts the optional parameters
  # @option opts [GetReleasesRequest] :get_releases_request 
  # @return [ReleaseSet]
  describe 'get_releases test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
