=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.81 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.81.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Athenian::CodeCheckMetricID
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Athenian::CodeCheckMetricID do
  let(:instance) { Athenian::CodeCheckMetricID.new }

  describe 'test an instance of CodeCheckMetricID' do
    it 'should create an instance of CodeCheckMetricID' do
      expect(instance).to be_instance_of(Athenian::CodeCheckMetricID)
    end
  end
end
