=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.81 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.81.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Athenian::DeleteEventsCacheRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Athenian::DeleteEventsCacheRequest do
  let(:instance) { Athenian::DeleteEventsCacheRequest.new }

  describe 'test an instance of DeleteEventsCacheRequest' do
    it 'should create an instance of DeleteEventsCacheRequest' do
      expect(instance).to be_instance_of(Athenian::DeleteEventsCacheRequest)
    end
  end
  describe 'test attribute "account"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "repositories"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "targets"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["release", "deployment"])
      # validator.allowable_values.each do |value|
      #   expect { instance.targets = value }.not_to raise_error
      # end
    end
  end

end
