=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.81 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.81.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Athenian::JIRAEpicChildAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Athenian::JIRAEpicChildAllOf do
  let(:instance) { Athenian::JIRAEpicChildAllOf.new }

  describe 'test an instance of JIRAEpicChildAllOf' do
    it 'should create an instance of JIRAEpicChildAllOf' do
      expect(instance).to be_instance_of(Athenian::JIRAEpicChildAllOf)
    end
  end
  describe 'test attribute "subtasks"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "prs"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
