=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.85 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.85.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0
=end

require 'date'
require 'time'

module Athenian
  # Summary of the deployed code.
  class DeploymentAnalysisCode
    # Number of deployed pull requests per repository.
    attr_accessor :prs

    # Number of changed lines in the deployed PRs per repository.
    attr_accessor :lines_prs

    # Number of changed lines in the deployment per repository.
    attr_accessor :lines_overall

    # Number of deployed PR commits per repository.
    attr_accessor :commits_prs

    # Number of deployed commits per repository.
    attr_accessor :commits_overall

    # JIRA issues mentioned in the deployed PRs.
    attr_accessor :jira

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'prs' => :'prs',
        :'lines_prs' => :'lines_prs',
        :'lines_overall' => :'lines_overall',
        :'commits_prs' => :'commits_prs',
        :'commits_overall' => :'commits_overall',
        :'jira' => :'jira'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'prs' => :'Hash<String, Integer>',
        :'lines_prs' => :'Hash<String, Integer>',
        :'lines_overall' => :'Hash<String, Integer>',
        :'commits_prs' => :'Hash<String, Integer>',
        :'commits_overall' => :'Hash<String, Integer>',
        :'jira' => :'Hash<String, Array<String>>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, 'The input argument (attributes) must be a hash in `Athenian::DeploymentAnalysisCode` initialize method'
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Athenian::DeploymentAnalysisCode`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'prs')
        if (value = attributes[:'prs']).is_a?(Hash)
          self.prs = value
        end
      end

      if attributes.key?(:'lines_prs')
        if (value = attributes[:'lines_prs']).is_a?(Hash)
          self.lines_prs = value
        end
      end

      if attributes.key?(:'lines_overall')
        if (value = attributes[:'lines_overall']).is_a?(Hash)
          self.lines_overall = value
        end
      end

      if attributes.key?(:'commits_prs')
        if (value = attributes[:'commits_prs']).is_a?(Hash)
          self.commits_prs = value
        end
      end

      if attributes.key?(:'commits_overall')
        if (value = attributes[:'commits_overall']).is_a?(Hash)
          self.commits_overall = value
        end
      end

      if attributes.key?(:'jira')
        if (value = attributes[:'jira']).is_a?(Hash)
          self.jira = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @prs.nil?
        invalid_properties.push('invalid value for "prs", prs cannot be nil.')
      end

      if @lines_prs.nil?
        invalid_properties.push('invalid value for "lines_prs", lines_prs cannot be nil.')
      end

      if @lines_overall.nil?
        invalid_properties.push('invalid value for "lines_overall", lines_overall cannot be nil.')
      end

      if @commits_prs.nil?
        invalid_properties.push('invalid value for "commits_prs", commits_prs cannot be nil.')
      end

      if @commits_overall.nil?
        invalid_properties.push('invalid value for "commits_overall", commits_overall cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @prs.nil?
      return false if @lines_prs.nil?
      return false if @lines_overall.nil?
      return false if @commits_prs.nil?
      return false if @commits_overall.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          prs == o.prs &&
          lines_prs == o.lines_prs &&
          lines_overall == o.lines_overall &&
          commits_prs == o.commits_prs &&
          commits_overall == o.commits_overall &&
          jira == o.jira
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [prs, lines_prs, lines_overall, commits_prs, commits_overall, jira].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Athenian.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
