=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.86 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.86.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0
=end

require 'date'
require 'time'

module Athenian
  class DeploymentMetricID
    COUNT = 'dep-count'.freeze
    DURATION_ALL = 'dep-duration-all'.freeze
    DURATION_SUCCESSFUL = 'dep-duration-successful'.freeze
    DURATION_FAILED = 'dep-duration-failed'.freeze
    SUCCESS_COUNT = 'dep-success-count'.freeze
    FAILURE_COUNT = 'dep-failure-count'.freeze
    SUCCESS_RATIO = 'dep-success-ratio'.freeze
    CHANGE_FAILURE_COUNT = 'dep-change-failure-count'.freeze
    CHANGE_FAILURE_RATIO = 'dep-change-failure-ratio'.freeze
    SIZE_PRS = 'dep-size-prs'.freeze
    SIZE_RELEASES = 'dep-size-releases'.freeze
    SIZE_LINES = 'dep-size-lines'.freeze
    SIZE_COMMITS = 'dep-size-commits'.freeze
    PRS_COUNT = 'dep-prs-count'.freeze
    RELEASES_COUNT = 'dep-releases-count'.freeze
    LINES_COUNT = 'dep-lines-count'.freeze
    COMMITS_COUNT = 'dep-commits-count'.freeze
    JIRA_ISSUES_COUNT = 'dep-jira-issues-count'.freeze
    JIRA_BUG_FIXES_COUNT = 'dep-jira-bug-fixes-count'.freeze

    def self.all_vars
      @all_vars ||= [COUNT, DURATION_ALL, DURATION_SUCCESSFUL, DURATION_FAILED, SUCCESS_COUNT, FAILURE_COUNT, SUCCESS_RATIO, CHANGE_FAILURE_COUNT, CHANGE_FAILURE_RATIO, SIZE_PRS, SIZE_RELEASES, SIZE_LINES, SIZE_COMMITS, PRS_COUNT, RELEASES_COUNT, LINES_COUNT, COMMITS_COUNT, JIRA_ISSUES_COUNT, JIRA_BUG_FIXES_COUNT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DeploymentMetricID.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DeploymentMetricID"
    end
  end
end
