=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.86 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.86.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0
=end

require 'date'
require 'time'

module Athenian
  class JIRAMetricID
    OPEN = 'jira-open'.freeze
    RESOLVED = 'jira-resolved'.freeze
    RAISED = 'jira-raised'.freeze
    ACKNOWLEDGED = 'jira-acknowledged'.freeze
    ACKNOWLEDGED_Q = 'jira-acknowledged-q'.freeze
    LIFE_TIME = 'jira-life-time'.freeze
    LIFE_TIME_BELOW_THRESHOLD_RATIO = 'jira-life-time-below-threshold-ratio'.freeze
    LEAD_TIME = 'jira-lead-time'.freeze
    LEAD_TIME_BELOW_THRESHOLD_RATIO = 'jira-lead-time-below-threshold-ratio'.freeze
    ACKNOWLEDGE_TIME = 'jira-acknowledge-time'.freeze
    ACKNOWLEDGE_TIME_BELOW_THRESHOLD_RATIO = 'jira-acknowledge-time-below-threshold-ratio'.freeze
    PR_LAG_TIME = 'jira-pr-lag-time'.freeze
    BACKLOG_TIME = 'jira-backlog-time'.freeze
    RESOLUTION_RATE = 'jira-resolution-rate'.freeze

    def self.all_vars
      @all_vars ||= [OPEN, RESOLVED, RAISED, ACKNOWLEDGED, ACKNOWLEDGED_Q, LIFE_TIME, LIFE_TIME_BELOW_THRESHOLD_RATIO, LEAD_TIME, LEAD_TIME_BELOW_THRESHOLD_RATIO, ACKNOWLEDGE_TIME, ACKNOWLEDGE_TIME_BELOW_THRESHOLD_RATIO, PR_LAG_TIME, BACKLOG_TIME, RESOLUTION_RATE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if JIRAMetricID.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #JIRAMetricID"
    end
  end
end
