=begin
This is an automatically generated file. DO NOT EDIT.

Generated from version 2.1.86 of the OpenAPI specification at
https://github.com/athenianco/api-spec/releases/tag/2.1.86.
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0
=end

require 'date'
require 'time'

module Athenian
  class PullRequestEvent
    CREATED = 'created'.freeze
    COMMITTED = 'committed'.freeze
    REVIEW_REQUESTED = 'review_requested'.freeze
    REVIEWED = 'reviewed'.freeze
    APPROVED = 'approved'.freeze
    CHANGES_REQUESTED = 'changes_requested'.freeze
    MERGED = 'merged'.freeze
    RELEASED = 'released'.freeze
    REJECTED = 'rejected'.freeze
    DEPLOYED = 'deployed'.freeze

    def self.all_vars
      @all_vars ||= [CREATED, COMMITTED, REVIEW_REQUESTED, REVIEWED, APPROVED, CHANGES_REQUESTED, MERGED, RELEASED, REJECTED, DEPLOYED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PullRequestEvent.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PullRequestEvent"
    end
  end
end
